//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImprowinCompanyWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblComment
    {
        public int CommentID { get; set; }
        public string CommentTitle { get; set; }
        
        public string CommentDesc { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDt { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModificationDt { get; set; }
        public int ActiveCD { get; set; }
    
        public virtual TblStatu TblStatu { get; set; }

       

       
    }

   
}
